[package]
name = "kitsune2"
version.workspace = true
description = "p2p / dht communication framework api"
license.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/kitsune2"
authors.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true

[dependencies]
bytes = { workspace = true }
kitsune2_api = { workspace = true }
kitsune2_core = { workspace = true }
kitsune2_gossip = { workspace = true }
kitsune2_transport_tx5 = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
kitsune2_gossip = { workspace = true }
kitsune2_test_utils = { workspace = true }
sbd-server = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
