extend = "../../Makefile.toml"

# runs clippy with default features, which covers `transport-iroh`
[tasks.clippy]
workspace = false
dependencies = ["clippy-transport-tx5-backend-go-pion"]

[tasks.clippy-transport-tx5-backend-go-pion]
workspace = false
command = "cargo"
args = [
  "clippy",
  "--all-targets",
  "--no-default-features",
  "--features",
  "transport-tx5-backend-go-pion",
  "--",
  "--deny=warnings",
]

# runs test with default features, which covers `transport-iroh`
[tasks.test]
workspace = false
dependencies = ["test-transport-tx5-backend-go-pion"]

[tasks.test-transport-tx5-backend-go-pion]
workspace = false
command = "cargo"
args = [
  "test",
  "--no-default-features",
  "--features",
  "transport-tx5-backend-go-pion",
  "--",
  "--nocapture",
]
