extend = "../../Makefile.toml"

# clippy is run with default features which covers iroh-relay.
[tasks.clippy]
workspace = false
dependencies = ["clippy-sbd"]

[tasks.clippy-sbd]
workspace = false
command = "cargo"
args = [
  "clippy",
  "--all-targets",
  "--no-default-features",
  "--features",
  "sbd",
  "--",
  "--deny=warnings",
]

# iroh-relay is tested by extending the root makefile which runs `cargo test`.
[tasks.test]
workspace = false
dependencies = ["test-sbd"]

[tasks.test-sbd]
workspace = false
command = "cargo"
args = ["test", "--no-default-features", "--features", "sbd"]
