[package]
name = "kitsune2_showcase"
version = "0.0.1-alpha"
description = "kitsune2 p2p / dht showcase app"
license = "Apache-2.0"
homepage = "https://github.com/holochain/kitsune2"
documentation = "https://docs.rs/kitsune2_showcase"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
keywords = ["holochain", "p2p", "dht", "networking"]
categories = ["network-programming"]
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive", "wrap_help"] }
kitsune2 = { workspace = true }
nu-ansi-term = "0.50.0"
reedline = { version = "0.38.0", features = ["external_printer"] }
tokio = { workspace = true, features = ["full"] }
