name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build

      - name: Lint
        run: cargo clippy --all-targets -- --deny warnings

      - name: Doc
        if: matrix.os == 'ubuntu-latest'
        run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps

      - name: Test
        run: cargo test

  ci_pass:
    if: ${{ always() }}
    name: "All Jobs Pass"
    runs-on: "ubuntu-latest"
    needs:
      - test
    steps:
      - name: check status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
