name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  static:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli@0.9.3

      - uses: Swatinem/rust-cache@v2

      - name: Toml format
        run: make static-toml

      - name: Format
        run: make fmt

      - name: Lint
        run: make clippy

      - name: Doc
        run: make doc

  test:
    needs: static
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: make build

      - name: Test
        run: make test

  ci_pass:
    if: ${{ always() }}
    runs-on: "ubuntu-latest"
    needs:
      - static
      - test
    steps:
      - name: check status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
